[build-system]
requires = [
  "jupyter_packaging~=0.7.0",
  "jupyterlab>=3.0.0rc9,==3.*",  # jlpm is used to build static js
  "setuptools>=40.8.0",
  "wheel"
]
build-backend = "setuptools.build_meta"
